### ISSUE TITLE
Crash when leaving running long term in background and come to foreground

### ISSUE THREAD

**Issue by teddyhoo** [teddyhoo/Android-Sitter-Mobile#19]
09-05 19:19:08.714 8195-8205/com.leashtime.sitterapp W/art: Suspending all threads took: 6.700ms
09-05 19:19:11.419 8195-16277/com.leashtime.sitterapp W/System.err: java.net.UnknownHostException: Unable to resolve host "leashtime.com": No address associated with hostname
09-05 19:19:11.424 8195-16277/com.leashtime.sitterapp W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
        at java.net.InetAddress.getAllByName(InetAddress.java:215)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-05 19:19:11.429 8195-16277/com.leashtime.sitterapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Posix.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
        at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
    	... 26 more
09-05 19:21:00.964 8195-8205/com.leashtime.sitterapp W/art: Suspending all threads took: 5.400ms
09-05 19:31:25.689 8195-23137/com.leashtime.sitterapp E/AndroidRuntime: FATAL EXCEPTION: Thread-34045
    Process: com.leashtime.sitterapp, PID: 8195
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:200)
        at android.os.Handler.<init>(Handler.java:114)
        at android.widget.Toast$TN.<init>(Toast.java:693)
        at android.widget.Toast.<init>(Toast.java:143)
        at android.widget.Toast.makeText(Toast.java:456)
        at com.leashtime.sitterapp.MainActivity.resendBadRequest(MainActivity.java:709)
        at com.leashtime.sitterapp.MainActivity.access$600(MainActivity.java:65)
        at com.leashtime.sitterapp.MainActivity$5.run(MainActivity.java:226)
        at java.lang.Thread.run(Thread.java:818)
09-05 19:31:30.899 8195-8195/com.leashtime.sitterapp E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by teddyhoo** [comment]
This is fixed. I have the Toast popup messages running on main ui thread. The error, i believe, is caused by not having a UI built but trying to add a component to it.

**Comment by teddyhoo** [comment]
I have run through some tests and while I cannot easily confirm that it fixed the crash problem, I feel comfortable that there are no unintended side effects.

**Comment by teddyhoo** [comment]
Running app in long running processes for several days and so far stable.
