### ISSUE TITLE
Android 2.0 Crash taking photo

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#22]
1. Disable camera permission for LeashTime.
2. Login to LeashTime.
3. Tap a pet to take a photo.
4. Answer "yes" to permssion request.
5. LeashTime has stopped.

WORKAROUND: Enable camera in LeashTime app permissions under Settings.

Trimmed stack:

09-24 16:09:08.728 1110-2142/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:892 com.android.server.location.GnssLocationProvider$7.addCircularHardwareGeofence:1605 android.hardware.location.GeofenceHardwareImpl.addCircularFence:283 android.hardware.location.GeofenceHardwareService$1.addCircularFence:102 android.hardware.location.IGeofenceHardware$Stub.onTransact:96
09-24 16:09:08.729 1110-2142/? E/ActivityManager: Sending non-protected broadcast com.motorola.location.instrumentation from system 1110:system/1000 pkg android
                                                  java.lang.Throwable
                                                      at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18259)
                                                      at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18859)
                                                      at android.app.ContextImpl.sendBroadcast(ContextImpl.java:898)
                                                      at com.android.server.location.GnssLocationProvider$7.addCircularHardwareGeofence(GnssLocationProvider.java:1605)
                                                      at android.hardware.location.GeofenceHardwareImpl.addCircularFence(GeofenceHardwareImpl.java:283)
                                                      at android.hardware.location.GeofenceHardwareService$1.addCircularFence(GeofenceHardwareService.java:102)
                                                      at android.hardware.location.IGeofenceHardware$Stub.onTransact(IGeofenceHardware.java:96)
                                                      at android.os.Binder.execTransact(Binder.java:565)
09-24 16:09:08.732 1110-2380/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:892 com.android.server.location.GnssLocationProvider$7.addCircularHardwareGeofence:1605 android.hardware.location.GeofenceHardwareImpl.addCircularFence:283 android.hardware.location.GeofenceHardwareService$1.addCircularFence:102 android.hardware.location.IGeofenceHardware$Stub.onTransact:96
09-24 16:09:08.732 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.733 1110-2380/? E/ActivityManager: Sending non-protected broadcast com.motorola.location.instrumentation from system 1110:system/1000 pkg android
                                                  java.lang.Throwable
                                                      at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18259)
                                                      at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18859)
                                                      at android.app.ContextImpl.sendBroadcast(ContextImpl.java:898)
                                                      at com.android.server.location.GnssLocationProvider$7.addCircularHardwareGeofence(GnssLocationProvider.java:1605)
                                                      at android.hardware.location.GeofenceHardwareImpl.addCircularFence(GeofenceHardwareImpl.java:283)
                                                      at android.hardware.location.GeofenceHardwareService$1.addCircularFence(GeofenceHardwareService.java:102)
                                                      at android.hardware.location.IGeofenceHardware$Stub.onTransact(IGeofenceHardware.java:96)
                                                      at android.os.Binder.execTransact(Binder.java:565)
09-24 16:09:08.734 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.735 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.738 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.739 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.740 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.743 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.745 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.746 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.746 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.747 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.747 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.749 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.750 2811-16444/? W/ctxmgr: [AclManager]No 2 for (accnt=account#67495021#, com.google.android.gms(10019):UserLocationProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2811). Was: 2 for 1, account#67495021#
09-24 16:09:08.752 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.752 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.754 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.754 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.756 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:08.974 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:09.129 16469-16469/? D/AndroidRuntime: Shutting down VM
09-24 16:09:09.134 16469-16469/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.leashtime.sitterapp, PID: 16469
                                                   java.lang.ClassCastException: com.leashtime.sitterapp.MainApplication cannot be cast to android.app.Activity
                                                       at com.leashtime.sitterapp.PhotoActivity$2.onClick(PhotoActivity.java:303)
                                                       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-24 16:09:09.139 1110-2381/? W/ActivityManager:   Force finishing activity com.leashtime.sitterapp/.PhotoActivity
09-24 16:09:09.156 1110-1174/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
09-24 16:09:09.157 2337-9471/? D/ProcSpeedReader: Failed to read freq stats from /sys/kernel/debug/clk/oxili_gfx3d_clk/rate_stats

**Comment by teddyhoo** [comment]
I am giving this low priority but it is indeed a bug.

**Comment by jodsmithLT** [comment]
I have a New client that was testing LeashTime and she ran into this issue on her Galaxy S9, luckily she asked about it and I was able to give her a workaround. Some trialing the system may consider this a deal breaker and not even ask.
