### ISSUE TITLE
Background -> foreground crash [CONCURRENT MODIFICATION EXCEPTION WITH VISIT DATA ARRAY]

### ISSUE THREAD

**Issue by teddyhoo** [teddyhoo/Android-Sitter-Mobile#6]
08-15 20:33:41.411 17315-17315/com.leashtime.sitterapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.leashtime.sitterapp, PID: 17315
    java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
        at com.leashtime.sitterapp.VisitsAndTracking.setLastValidLocation(VisitsAndTracking.java:758)
        at com.leashtime.sitterapp.TrackerServiceSitter$MyServiceRunnable.onLocationChanged(TrackerServiceSitter.java:300)
        at com.google.android.gms.internal.location.zzay.notifyListener(Unknown Source)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source)
        at com.google.android.gms.common.api.internal.ListenerHolder$zza.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by teddyhoo** [comment]
I'm going to resolve this as a duplicate. This is related to all the threading changes. Threading should either resolve or exacerbate the issue but ti should be tracked there instead.
